In [218]:
#Gerekli kütüphaneleri import ettim
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [219]:
'''
work_year: Maaşın ödendiği yıl.
experience_level Aşağıdaki olası değerlerle yıl boyunca işteki deneyim seviyesi: 
    EN Giriş seviyesi / Junior MI Orta seviye / Orta SE Kıdemli seviye / Expert EX Yönetici seviyesi / Direktör
    
employment_type:PT Yarı zamanlı FT Tam zamanlı CT Sözleşmeli FL Serbest   

job_title: Yıl boyunca çalışılan rol.

salary:Ödenen toplam brüt maaş tutarı.

salary_currency:Bir ISO 4217 para birimi kodu olarak ödenen maaşın para birimi.

salaryinusd:USD cinsinden maaş

employee_residence:Çalışanın çalışma yılı boyunca ISO 3166 ülke kodu olarak birincil ikamet ettiği ülke.

remote_ratio:Uzaktan yapılan toplam iş miktarı, olası değerler aşağıdaki gibidir: 
    0 Uzaktan çalışma yok (%20'den az) 50 Kısmen uzak 100 Tamamen uzak (%80'den fazla)
    
company_location:ISO 3166 ülke kodu olarak işverenin ana ofisinin veya sözleşmeli şubesinin bulunduğu ülke.

company_size:Yıl içinde şirkette çalışan ortalama kişi sayısı: 
    S 50'den az çalışan (küçük) M 50 ila 250 çalışan (orta) L 250'den fazla çalışan (büyük)

'''
print("-")

-

In [220]:
data=pd.read_csv("ds_salaries.csv")#veriyi hazırladım
data.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [221]:
data.drop("Unnamed: 0",axis=1,inplace=True)#"Unnamed: 0" sütununu veriden kaldırdım
#Label Encoder:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
data["experience_level"]=le.fit_transform(data["experience_level"])
data["employment_type"]=le.fit_transform(data["employment_type"])
data["job_title"]=le.fit_transform(data["job_title"])
data["salary_currency"]=le.fit_transform(data["salary_currency"])
data["employee_residence"]=le.fit_transform(data["employee_residence"])
data["company_location"]=le.fit_transform(data["company_location"])
data["company_size"]=le.fit_transform(data["company_size"])
data.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2020,2,2,22,70000,7,79833,14,0,12,0
1,2020,3,2,41,260000,16,260000,32,0,29,2
2,2020,3,2,7,85000,8,109024,20,50,18,1
3,2020,2,2,47,20000,16,20000,23,0,20,2
4,2020,3,2,38,150000,16,150000,55,50,48,0

In [222]:
data.isnull().sum()#Veride boş değer olup olmadığını kontrol ettim

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [223]:
x=data.drop("salary",axis=1)#Bağımsız değişken
y=data["salary"]#Bağımlı değişken

#Model hakkında bilgi edindim
model=sm.OLS(y,x).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                 salary   R-squared (uncentered):                   0.068
Model:                            OLS   Adj. R-squared (uncentered):              0.052
Method:                 Least Squares   F-statistic:                              4.345
Date:                Tue, 02 Aug 2022   Prob (F-statistic):                    6.84e-06
Time:                        15:02:45   Log-Likelihood:                         -9502.4
No. Observations:                 607   AIC:                                  1.902e+04
Df Residuals:                     597   BIC:                                  1.907e+04
Df Model:                          10
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
work_year            561.0039    315.815      1.776      0.076     -59.239    1181.247
experience_level    7120.3292   6.42e+04      0.111      0.912   -1.19e+05    1.33e+05
employment_type    -8.368e+04   2.68e+05     -0.313      0.755   -6.09e+05    4.42e+05
job_title           3127.7886   6190.388      0.505      0.614   -9029.797    1.53e+04
salary_currency    -3.301e+04   2.42e+04     -1.364      0.173   -8.05e+04    1.45e+04
salary_in_usd         -1.3153      1.065     -1.235      0.217      -3.407       0.776
employee_residence -1.087e+04   8007.407     -1.358      0.175   -2.66e+04    4854.175
remote_ratio         329.0246   1561.837      0.211      0.833   -2738.338    3396.387
company_location    1.212e+04   9588.106      1.264      0.207   -6708.545     3.1e+04
company_size        -2.04e+05   9.82e+04     -2.077      0.038   -3.97e+05   -1.11e+04
==============================================================================
Omnibus:                     1184.279   Durbin-Watson:                   1.911
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1468050.730
Skew:                          13.675   Prob(JB):                         0.00
Kurtosis:                     242.367   Cond. No.                     5.71e+05
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 5.71e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [224]:
#Veriyi test ve eğitim kümelerine ayırdım
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

#Standard Scaler işlemi Yaptım(Veriyi aynı dünyaya indirgemek)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [225]:
#Linear Regression
from sklearn.linear_model import LinearRegression
lg=LinearRegression()
lg.fit(x_train,y_train)
y_pred=lg.predict(x_test)
print(r2_score(y_test,y_pred))

0.01045181618849933

In [226]:
#Polynomial Features
from sklearn.preprocessing import PolynomialFeatures
pf=PolynomialFeatures(degree=8)
x_poly=pf.fit_transform(x_train)
lg2=LinearRegression()
lg2.fit(x_poly,y_train)
y_pred=lg2.predict(pf.fit_transform(x_test))
print(r2_score(y_test,y_pred))

-648.8736747076682

In [227]:
#Support Vector Machine
from sklearn.svm import SVR
svr=SVR(kernel="rbf")
svr.fit(x_train,y_train)
y_pred=svr.predict(x_test)
print(r2_score(y_test,y_pred))

-0.011877945673214763

In [228]:
#Decision Tree Regressor
from sklearn.tree import DecisionTreeRegressor
dc=DecisionTreeRegressor()
dc.fit(x_train,y_train)
y_pred=dc.predict(x_test)
print(r2_score(y_test,y_pred))

0.06903864742221733

In [229]:
#Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(n_estimators=8)
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
print(r2_score(y_test,y_pred))

0.027414640396075107

In [230]:
#XGBOOST
from xgboost import XGBRegressor
xgb=XGBRegressor()
xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)
print(r2_score(y_test,y_pred))

0.06513686463479007

In [231]:
x.shape

(607, 10)

In [232]:
#YSA:Yapay Sinir Ağları
import tensorflow
from keras.models import Sequential 
from keras.layers import Dense

model=Sequential()
model.add(Dense(10,activation="relu"))
model.add(Dense(5,activation="relu"))
model.add(Dense(1,activation="relu"))
model.compile(optimizer="adam",loss="mse")
model.fit(x_train,y_train,epochs=10)
y_pred=model.predict(x_test)
y_pred=y_pred>5
print("-"*80)
print(r2_score(y_test,y_pred))

Epoch 1/10
14/14 [==============================] - 0s 2ms/step - loss: 1158726549504.0000
Epoch 2/10
14/14 [==============================] - 0s 2ms/step - loss: 1158726418432.0000
Epoch 3/10
14/14 [==============================] - 0s 2ms/step - loss: 1158726287360.0000
Epoch 4/10
14/14 [==============================] - 0s 2ms/step - loss: 1158726287360.0000
Epoch 5/10
14/14 [==============================] - 0s 2ms/step - loss: 1158726287360.0000
Epoch 6/10
14/14 [==============================] - 0s 2ms/step - loss: 1158726287360.0000
Epoch 7/10
14/14 [==============================] - 0s 2ms/step - loss: 1158726287360.0000
Epoch 8/10
14/14 [==============================] - 0s 2ms/step - loss: 1158726287360.0000
Epoch 9/10
14/14 [==============================] - 0s 2ms/step - loss: 1158726287360.0000
Epoch 10/10
14/14 [==============================] - 0s 2ms/step - loss: 1158726156288.0000
6/6 [==============================] - 0s 2ms/step
--------------------------------------------------------------------------------
-0.025069127612562303

In [233]:
model=sm.OLS(y,x).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                 salary   R-squared (uncentered):                   0.068
Model:                            OLS   Adj. R-squared (uncentered):              0.052
Method:                 Least Squares   F-statistic:                              4.345
Date:                Tue, 02 Aug 2022   Prob (F-statistic):                    6.84e-06
Time:                        15:02:47   Log-Likelihood:                         -9502.4
No. Observations:                 607   AIC:                                  1.902e+04
Df Residuals:                     597   BIC:                                  1.907e+04
Df Model:                          10
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
work_year            561.0039    315.815      1.776      0.076     -59.239    1181.247
experience_level    7120.3292   6.42e+04      0.111      0.912   -1.19e+05    1.33e+05
employment_type    -8.368e+04   2.68e+05     -0.313      0.755   -6.09e+05    4.42e+05
job_title           3127.7886   6190.388      0.505      0.614   -9029.797    1.53e+04
salary_currency    -3.301e+04   2.42e+04     -1.364      0.173   -8.05e+04    1.45e+04
salary_in_usd         -1.3153      1.065     -1.235      0.217      -3.407       0.776
employee_residence -1.087e+04   8007.407     -1.358      0.175   -2.66e+04    4854.175
remote_ratio         329.0246   1561.837      0.211      0.833   -2738.338    3396.387
company_location    1.212e+04   9588.106      1.264      0.207   -6708.545     3.1e+04
company_size        -2.04e+05   9.82e+04     -2.077      0.038   -3.97e+05   -1.11e+04
==============================================================================
Omnibus:                     1184.279   Durbin-Watson:                   1.911
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1468050.730
Skew:                          13.675   Prob(JB):                         0.00
Kurtosis:                     242.367   Cond. No.                     5.71e+05
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 5.71e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [234]:
#p-value değeri yüksek olan değişkenleri veriden çıkardım
data.drop("experience_level",axis=1,inplace=True)
data.drop("employment_type",axis=1,inplace=True)
data.drop("remote_ratio",axis=1,inplace=True)
data.drop("job_title",axis=1,inplace=True)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
x=data.drop("salary",axis=1)
y=data["salary"]
model=sm.OLS(y,x).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                 salary   R-squared (uncentered):                   0.067
Model:                            OLS   Adj. R-squared (uncentered):              0.058
Method:                 Least Squares   F-statistic:                              7.212
Date:                Tue, 02 Aug 2022   Prob (F-statistic):                    1.91e-07
Time:                        15:02:47   Log-Likelihood:                         -9502.6
No. Observations:                 607   AIC:                                  1.902e+04
Df Residuals:                     601   BIC:                                  1.904e+04
Df Model:                           6
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
work_year            527.1844    104.212      5.059      0.000     322.521     731.848
salary_currency    -3.402e+04    2.4e+04     -1.416      0.157   -8.12e+04    1.32e+04
salary_in_usd         -1.1309      1.003     -1.128      0.260      -3.101       0.839
employee_residence -1.071e+04   7965.882     -1.344      0.179   -2.64e+04    4938.257
company_location    1.188e+04   9480.518      1.253      0.211   -6743.651    3.05e+04
company_size       -2.036e+05   9.78e+04     -2.082      0.038   -3.96e+05   -1.15e+04
==============================================================================
Omnibus:                     1184.508   Durbin-Watson:                   1.908
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1469137.989
Skew:                          13.681   Prob(JB):                         0.00
Kurtosis:                     242.456   Cond. No.                     2.09e+05
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 2.09e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [235]:
xgb2=XGBRegressor()
xgb2.fit(x_train,y_train)
y_pred=xgb2.predict(x_test)
print("XGBOOST")
print(r2_score(y_test,y_pred))

rf2=RandomForestRegressor(n_estimators=10)
rf2.fit(x_train,y_train)
print("RANDOM FOREST")
print(r2_score(y_test,rf2.predict(x_test)))

XGBOOST
0.06513686463479007
RANDOM FOREST
0.03651710348682358